# admin/config.yml - EN BASİT VE EN STABİL GİRİŞ YÖNTEMİ

backend:
  name: github
  repo: Kaevros/kaevros.github.io
  branch: main
  
  # DİKKAT: Karmaşık ayarlar kaldırıldı, yerine bu basit yöntem eklendi.
  # Bu, halka açık repolar için en sorunsuz çalışan yöntemdir.
  auth_type: implicit
  
media_folder: "assets/images"
public_folder: "/assets/images"
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Yazılar"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Kısa Açıklama (SEO için)", name: "description", widget: "string" }
      - { label: "Etiketler", name: "tags", widget: "list", required: false }
      - { label: "Kapak Fotoğrafı (İsteğe Bağlı)", name: "image", widget: "image", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }