# admin/config.yml

backend:
  name: github
  repo: Kaevros/kaevros.github.io
  branch: main
  site_domain: kaevros.github.io

# DİKKAT: app_id satırı eklendi.
# Bu, GitHub'a kendi uygulamamız üzerinden bağlandığımızı söyler.
app_id: Ov23li88PIl7iF9Br2Ck
  
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Yazılar"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Kısa Açıklama (SEO için)", name: "description", widget: "string" }
      - { label: "Etiketler", name: "tags", widget: "list", required: false }
      - { label: "Kapak Fotoğrafı (İsteğe Bağlı)", name: "image", widget: "image", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }