# backend: GitHub'ı arka plan olarak kullanacağımızı belirtiyoruz.
backend:
  name: github
  repo: Kaevros/kaevros.github.io # GitHub kullanıcı adınız ve depo adınız
  branch: main # Deponuzun ana dalı (genellikle 'main' veya 'master')

# Medya dosyaları (resimler vb.) yüklenirse nereye kaydedileceği.
media_folder: "images/uploads"
public_folder: "/images/uploads"

# Yönetilecek içerik koleksiyonları.
collections:
  - name: "posts"
    label: "Yazılar" # Arayüzde görünecek etiket
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    path: "{{slug}}.html"
    
    frontmatter_delimiter: "---"
    editor:
      preview: false
    
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", picker_utc: true}
      - label: "İçerik"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Sayfa Yönetimi"
    files:
      - label: "Ana Sayfa Ayarları" # Burayı güncelledik
        name: "index_page"
        file: "index.html"
        fields:
          - {label: "Blog Başlığı", name: "blog_title", widget: "string", default: "Mustafa Günay"} # Yeni alan
          - label: "Son Yazılar Bölüm Başlığı"
            name: "homepage_title"
            widget: "string"
            default: "Son Yazılar"
          - label: "Ana Sayfa Açıklaması"
            name: "homepage_description"
            widget: "markdown"
            required: false

      - label: "Tüm Yazılar Sayfası Ayarları" # Burayı güncelledik
        name: "posts_list_page"
        file: "posts.html"
        fields:
          - label: "Sayfa Başlığı"
            name: "page_title"
            widget: "string"
            default: "Tüm Blog Yazılarım"
          - label: "Sayfa Açıklaması"
            name: "page_description"
            widget: "markdown"
            required: false

      - label: "Hakkımda Sayfası Ayarları" # Hakkımda sayfası için ekledik
        name: "about_page"
        file: "about.html"
        fields:
          - label: "Hakkımda Başlığı"
            name: "about_title"
            widget: "string"
            default: "Hakkımda"
          - label: "Hakkımda İçeriği"
            name: "about_content"
            widget: "markdown"

      - label: "İletişim Sayfası Ayarları" # İletişim sayfası için ekledik
        name: "contact_page"
        file: "contact.html"
        fields:
          - label: "İletişim Başlığı"
            name: "contact_title"
            widget: "string"
            default: "İletişim"
          - label: "İletişim Açıklaması"
            name: "contact_description"
            widget: "markdown"
