# admin/config.yml - GİRİŞ HATASINI ÇÖZEN NİHAİ VERSİYON

backend:
  name: github
  repo: Kaevros/kaevros.github.io
  branch: main
  
  # DİKKAT: Bu satırların harfi harfine doğru olduğundan emin olun.
  base_url: https://api.decapcms.org
  auth_endpoint: auth

# Bu, bir önceki adımda GitHub'da oluşturduğun OAuth uygulamasının Client ID'sidir.
app_id: Ov23li88PIl7iF9Br2Ck
  
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Yazılar"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Kısa Açıklama (SEO için)", name: "description", widget: "string" }
      - { label: "Etiketler", name: "tags", widget: "list", required: false }
      - { label: "Kapak Fotoğrafı (İsteğe Bağlı)", name: "image", widget: "image", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }