# backend: GitHub'ı arka plan olarak kullanacağımızı belirtiyoruz.
backend:
  name: github
  repo: Kaevros/kaevros.github.io # Kendi GitHub kullanıcı adınızı ve depo adınızı yazın.
  branch: main # Deponuzun ana dalı (genellikle 'main' veya 'master')

# Medya dosyaları (resimler vb.) yüklenirse nereye kaydedileceği.
# `public_folder` web'den erişilen yolu, `media_folder` ise depodaki fiziksel yolu belirtir.
media_folder: "images/uploads"
public_folder: "/images/uploads"

# Yönetilecek içerik koleksiyonları.
collections:
  - name: "posts" # Koleksiyonun iç adı (benzersiz olmalı)
    label: "Yazılar" # Arayüzde görünecek etiket
    folder: "posts" # Yazıların kaydedileceği klasör
    create: true # Arayüzden yeni yazı oluşturmaya izin ver
    slug: "{{slug}}" # Dosya adını başlıktan otomatik oluşturur (ör: "ilk-blog-yazim")
    extension: "html" # Dosya uzantısı .html olacak
    format: "frontmatter" # YAML frontmatter kullanacağımızı belirtiyoruz.
    path: "{{slug}}.html" # Decap CMS'in dosyaları nasıl kaydedeceğini belirtir.
    
    frontmatter_delimiter: "---"
    editor:
      preview: false # Canlı önizlemeyi kapatabiliriz, karmaşık HTML için faydalı.
    
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", picker_utc: true}
      - label: "İçerik"
        name: "body"
        widget: "markdown" # Yazılarınızı kolayca Markdown formatında yazmanızı sağlar.

  - name: "pages"
    label: "Sayfa Yönetimi"
    files:
      - label: "Ana Sayfa Yazı Listesi"
        name: "index_page"
        file: "index.html"
        fields:
          - label: "Ana Sayfa Başlığı"
            name: "homepage_title"
            widget: "string"
            default: "Son Yazılar"
          - label: "Ana Sayfa Açıklaması"
            name: "homepage_description"
            widget: "markdown"
            required: false

      - label: "Tüm Yazılar Sayfası"
        name: "posts_list_page"
        file: "posts.html"
        fields:
          - label: "Sayfa Başlığı"
            name: "page_title"
            widget: "string"
            default: "Tüm Blog Yazılarım"
          - label: "Sayfa Açıklaması"
            name: "page_description"
            widget: "markdown"
            required: false
