backend:
  name: github
  repo: Kaevros/kaevros.github.io # SENİN KULLANICI ADIN / REPO ADIN
  branch: main # Deponuzun ana dalı 'main' ise bu şekilde bırakın. 'master' ise onu yazın.
  
# Medya dosyaları (resimler vb.) yüklendiğinde nereye kaydedilecek.
media_folder: "assets/uploads" # Resimlerin yükleneceği klasör
public_folder: "/assets/uploads" # Resimlerin sitede görüneceği yol

# Yönetilecek içerik koleksiyonları
collections:
  # Blog yazılarını yöneteceğimiz koleksiyon
  - name: "posts" # Koleksiyonun teknik adı
    label: "Blog Yazıları" # Arayüzde görünecek etiket
    folder: "_posts" # Jekyll ve GitHub Pages ile uyumlu olması için _posts klasörünü kullanalım
    create: true # Yeni yazı oluşturmaya izin ver
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Dosya adını '2025-07-22-yeni-yazim' formatında oluşturur
    extension: "md" # Dosya uzantısı Markdown olsun
    format: "frontmatter" # Jekyll uyumlu format
    fields: # Her yazı için doldurulacak alanlar
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Etiketler (virgülle ayırın)", name: "tags", widget: "string", required: false }
      - { label: "Kısa Açıklama", name: "excerpt", widget: "text", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }
